services:
  resilmesh-sap-nse-backend:
    container_name: resilmesh-sap-nse-backend
    build:
      context: ./servers
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NEO4J_SERVER_URL=bolt://resilmesh-sap-neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=supertestovaciheslo
      - ISIM_API_URL=http://resilmesh-sap-isim-automation:5000
    volumes:
      - ./servers/data:/app/data
    networks:
      - resilmesh_network

  resilmesh-sap-nse-frontend:
    container_name: resilmesh-sap-nse-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    depends_on:
      - resilmesh-sap-nse-backend
    networks:
      - resilmesh_network

networks:
  resilmesh_network:
    external: true