services:
  resilmesh_sap_nse_backend:
    container_name: resilmesh_sap_nse_backend
    build:
      context: ./servers
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NEO4J_SERVER_URL=bolt://resilmesh_sap_isim_neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=supertestovaciheslo
      - ISIM_API_URL=http://resilmesh_sap_isim_automation:5000
    volumes:
      - ./servers/data:/app/data
    networks:
      - resilmesh_network

  resilmesh_sap_nse_frontend:
    container_name: resilmesh_sap_nse_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    depends_on:
      - resilmesh_sap_nse_backend
    networks:
      - resilmesh_network

networks:
  resilmesh_network:
    external: true